logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
spring:
  datasource:
    generate-unique-name: false
    name: githubrepositoriesdb
  h2:
    console:
      enabled: true
retrofit-config:
  base-url: https://api.github.com